name: Build

on: 
  workflow_dispatch:
  push: 
    branches: 
      - 'main'
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/build.yml'
  pull_request:
    branches: '*'
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/build.yml'

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../ -A Win32
      
      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Create folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          cd ..
          mv ./build/src/Release/discord-rpc.asi ./dist/discord-rpc.asi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: discord-rpc
          path: dist/*